# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FailureReason(str, Enum):
    """
    FailureReason
    """

    """
    allowed enum values
    """
    ACCESS_DENIED = 'access_denied'
    PROXY_ERROR = 'proxy_error'
    NOT_FOUND = 'not_found'
    SCRAP_SERVICE_OVERLOAD = 'scrap_service_overload'
    DATA_ISSUE = 'data_issue'
    PROCESS_SERVICE_OVERLOAD = 'process_service_overload'
    NO_SECTIONS = 'no_sections'
    NOT_ON_SALE = 'not_on_sale'
    SOLD_OUT = 'sold_out'
    DATA_PROCESS_ERROR = 'data_process_error'
    SEATS_FOUND_WITH_NO_MAP = 'seats_found_with_no_map'
    DATA_STORAGE_ERROR = 'data_storage_error'
    DUPLICATE_PLACE_ID = 'duplicate_place_id'
    TIMEOUT = 'timeout'
    TRIGGER_PROCESS_ERROR = 'trigger_process_error'
    DEFAULT = 'default'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FailureReason from a JSON string"""
        return cls(json.loads(json_str))


