# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from trigger_service_logger_client.models.scraping_timing_time_series_sample_schema import ScrapingTimingTimeSeriesSampleSchema
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ScrapingTimingTimeSeriesBucketSchema(BaseModel):
    """
    ScrapingTimingTimeSeriesBucketSchema
    """ # noqa: E501
    time: datetime
    ticketmaster: Optional[ScrapingTimingTimeSeriesSampleSchema]
    vividseats: Optional[ScrapingTimingTimeSeriesSampleSchema]
    evenue: Optional[ScrapingTimingTimeSeriesSampleSchema]
    tickpick: Optional[ScrapingTimingTimeSeriesSampleSchema]
    stubhub: Optional[ScrapingTimingTimeSeriesSampleSchema]
    gotickets: Optional[ScrapingTimingTimeSeriesSampleSchema]
    milb: Optional[ScrapingTimingTimeSeriesSampleSchema]
    mlb: Optional[ScrapingTimingTimeSeriesSampleSchema]
    playhousesquare: Optional[ScrapingTimingTimeSeriesSampleSchema]
    telecharge: Optional[ScrapingTimingTimeSeriesSampleSchema]
    mpv: Optional[ScrapingTimingTimeSeriesSampleSchema]
    etix: Optional[ScrapingTimingTimeSeriesSampleSchema]
    ovationtix: Optional[ScrapingTimingTimeSeriesSampleSchema]
    __properties: ClassVar[List[str]] = ["time", "ticketmaster", "vividseats", "evenue", "tickpick", "stubhub", "gotickets", "milb", "mlb", "playhousesquare", "telecharge", "mpv", "etix", "ovationtix"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScrapingTimingTimeSeriesBucketSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ticketmaster
        if self.ticketmaster:
            _dict['ticketmaster'] = self.ticketmaster.to_dict()
        # override the default output from pydantic by calling `to_dict()` of vividseats
        if self.vividseats:
            _dict['vividseats'] = self.vividseats.to_dict()
        # override the default output from pydantic by calling `to_dict()` of evenue
        if self.evenue:
            _dict['evenue'] = self.evenue.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tickpick
        if self.tickpick:
            _dict['tickpick'] = self.tickpick.to_dict()
        # override the default output from pydantic by calling `to_dict()` of stubhub
        if self.stubhub:
            _dict['stubhub'] = self.stubhub.to_dict()
        # override the default output from pydantic by calling `to_dict()` of gotickets
        if self.gotickets:
            _dict['gotickets'] = self.gotickets.to_dict()
        # override the default output from pydantic by calling `to_dict()` of milb
        if self.milb:
            _dict['milb'] = self.milb.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mlb
        if self.mlb:
            _dict['mlb'] = self.mlb.to_dict()
        # override the default output from pydantic by calling `to_dict()` of playhousesquare
        if self.playhousesquare:
            _dict['playhousesquare'] = self.playhousesquare.to_dict()
        # override the default output from pydantic by calling `to_dict()` of telecharge
        if self.telecharge:
            _dict['telecharge'] = self.telecharge.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mpv
        if self.mpv:
            _dict['mpv'] = self.mpv.to_dict()
        # override the default output from pydantic by calling `to_dict()` of etix
        if self.etix:
            _dict['etix'] = self.etix.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ovationtix
        if self.ovationtix:
            _dict['ovationtix'] = self.ovationtix.to_dict()
        # set to None if ticketmaster (nullable) is None
        # and model_fields_set contains the field
        if self.ticketmaster is None and "ticketmaster" in self.model_fields_set:
            _dict['ticketmaster'] = None

        # set to None if vividseats (nullable) is None
        # and model_fields_set contains the field
        if self.vividseats is None and "vividseats" in self.model_fields_set:
            _dict['vividseats'] = None

        # set to None if evenue (nullable) is None
        # and model_fields_set contains the field
        if self.evenue is None and "evenue" in self.model_fields_set:
            _dict['evenue'] = None

        # set to None if tickpick (nullable) is None
        # and model_fields_set contains the field
        if self.tickpick is None and "tickpick" in self.model_fields_set:
            _dict['tickpick'] = None

        # set to None if stubhub (nullable) is None
        # and model_fields_set contains the field
        if self.stubhub is None and "stubhub" in self.model_fields_set:
            _dict['stubhub'] = None

        # set to None if gotickets (nullable) is None
        # and model_fields_set contains the field
        if self.gotickets is None and "gotickets" in self.model_fields_set:
            _dict['gotickets'] = None

        # set to None if milb (nullable) is None
        # and model_fields_set contains the field
        if self.milb is None and "milb" in self.model_fields_set:
            _dict['milb'] = None

        # set to None if mlb (nullable) is None
        # and model_fields_set contains the field
        if self.mlb is None and "mlb" in self.model_fields_set:
            _dict['mlb'] = None

        # set to None if playhousesquare (nullable) is None
        # and model_fields_set contains the field
        if self.playhousesquare is None and "playhousesquare" in self.model_fields_set:
            _dict['playhousesquare'] = None

        # set to None if telecharge (nullable) is None
        # and model_fields_set contains the field
        if self.telecharge is None and "telecharge" in self.model_fields_set:
            _dict['telecharge'] = None

        # set to None if mpv (nullable) is None
        # and model_fields_set contains the field
        if self.mpv is None and "mpv" in self.model_fields_set:
            _dict['mpv'] = None

        # set to None if etix (nullable) is None
        # and model_fields_set contains the field
        if self.etix is None and "etix" in self.model_fields_set:
            _dict['etix'] = None

        # set to None if ovationtix (nullable) is None
        # and model_fields_set contains the field
        if self.ovationtix is None and "ovationtix" in self.model_fields_set:
            _dict['ovationtix'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScrapingTimingTimeSeriesBucketSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "time": obj.get("time"),
            "ticketmaster": ScrapingTimingTimeSeriesSampleSchema.from_dict(obj["ticketmaster"]) if obj.get("ticketmaster") is not None else None,
            "vividseats": ScrapingTimingTimeSeriesSampleSchema.from_dict(obj["vividseats"]) if obj.get("vividseats") is not None else None,
            "evenue": ScrapingTimingTimeSeriesSampleSchema.from_dict(obj["evenue"]) if obj.get("evenue") is not None else None,
            "tickpick": ScrapingTimingTimeSeriesSampleSchema.from_dict(obj["tickpick"]) if obj.get("tickpick") is not None else None,
            "stubhub": ScrapingTimingTimeSeriesSampleSchema.from_dict(obj["stubhub"]) if obj.get("stubhub") is not None else None,
            "gotickets": ScrapingTimingTimeSeriesSampleSchema.from_dict(obj["gotickets"]) if obj.get("gotickets") is not None else None,
            "milb": ScrapingTimingTimeSeriesSampleSchema.from_dict(obj["milb"]) if obj.get("milb") is not None else None,
            "mlb": ScrapingTimingTimeSeriesSampleSchema.from_dict(obj["mlb"]) if obj.get("mlb") is not None else None,
            "playhousesquare": ScrapingTimingTimeSeriesSampleSchema.from_dict(obj["playhousesquare"]) if obj.get("playhousesquare") is not None else None,
            "telecharge": ScrapingTimingTimeSeriesSampleSchema.from_dict(obj["telecharge"]) if obj.get("telecharge") is not None else None,
            "mpv": ScrapingTimingTimeSeriesSampleSchema.from_dict(obj["mpv"]) if obj.get("mpv") is not None else None,
            "etix": ScrapingTimingTimeSeriesSampleSchema.from_dict(obj["etix"]) if obj.get("etix") is not None else None,
            "ovationtix": ScrapingTimingTimeSeriesSampleSchema.from_dict(obj["ovationtix"]) if obj.get("ovationtix") is not None else None
        })
        return _obj


