# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ScrapingVendorStatsSingleSchema(BaseModel):
    """
    ScrapingVendorStatsSingleSchema
    """ # noqa: E501
    total_requests: StrictInt
    success_rate: Optional[Union[StrictFloat, StrictInt]]
    avg_scrape_time: Optional[StrictStr]
    error_rate: Optional[Union[StrictFloat, StrictInt]]
    __properties: ClassVar[List[str]] = ["total_requests", "success_rate", "avg_scrape_time", "error_rate"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScrapingVendorStatsSingleSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if success_rate (nullable) is None
        # and model_fields_set contains the field
        if self.success_rate is None and "success_rate" in self.model_fields_set:
            _dict['success_rate'] = None

        # set to None if avg_scrape_time (nullable) is None
        # and model_fields_set contains the field
        if self.avg_scrape_time is None and "avg_scrape_time" in self.model_fields_set:
            _dict['avg_scrape_time'] = None

        # set to None if error_rate (nullable) is None
        # and model_fields_set contains the field
        if self.error_rate is None and "error_rate" in self.model_fields_set:
            _dict['error_rate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScrapingVendorStatsSingleSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total_requests": obj.get("total_requests"),
            "success_rate": obj.get("success_rate"),
            "avg_scrape_time": obj.get("avg_scrape_time"),
            "error_rate": obj.get("error_rate")
        })
        return _obj


