# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ScrapingTimingStatsSingleSchema(BaseModel):
    """
    ScrapingTimingStatsSingleSchema
    """ # noqa: E501
    avg_scraping_time: Optional[StrictStr]
    avg_data_processing_time: Optional[StrictStr]
    avg_total_etl_time: Optional[StrictStr]
    avg_scrape_queue_duration: Optional[StrictStr]
    total_scrapes: StrictInt
    error_count: StrictInt
    non_error_failure_count: StrictInt
    __properties: ClassVar[List[str]] = ["avg_scraping_time", "avg_data_processing_time", "avg_total_etl_time", "avg_scrape_queue_duration", "total_scrapes", "error_count", "non_error_failure_count"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScrapingTimingStatsSingleSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if avg_scraping_time (nullable) is None
        # and model_fields_set contains the field
        if self.avg_scraping_time is None and "avg_scraping_time" in self.model_fields_set:
            _dict['avg_scraping_time'] = None

        # set to None if avg_data_processing_time (nullable) is None
        # and model_fields_set contains the field
        if self.avg_data_processing_time is None and "avg_data_processing_time" in self.model_fields_set:
            _dict['avg_data_processing_time'] = None

        # set to None if avg_total_etl_time (nullable) is None
        # and model_fields_set contains the field
        if self.avg_total_etl_time is None and "avg_total_etl_time" in self.model_fields_set:
            _dict['avg_total_etl_time'] = None

        # set to None if avg_scrape_queue_duration (nullable) is None
        # and model_fields_set contains the field
        if self.avg_scrape_queue_duration is None and "avg_scrape_queue_duration" in self.model_fields_set:
            _dict['avg_scrape_queue_duration'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScrapingTimingStatsSingleSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "avg_scraping_time": obj.get("avg_scraping_time"),
            "avg_data_processing_time": obj.get("avg_data_processing_time"),
            "avg_total_etl_time": obj.get("avg_total_etl_time"),
            "avg_scrape_queue_duration": obj.get("avg_scrape_queue_duration"),
            "total_scrapes": obj.get("total_scrapes"),
            "error_count": obj.get("error_count"),
            "non_error_failure_count": obj.get("non_error_failure_count")
        })
        return _obj


