# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class ScrapedEventsCountSchema(BaseModel):
    """
    ScrapedEventsCountSchema
    """ # noqa: E501
    ticketmaster: StrictInt
    vividseats: StrictInt
    evenue: StrictInt
    tickpick: StrictInt
    stubhub: StrictInt
    gotickets: StrictInt
    milb: StrictInt
    mlb: StrictInt
    playhousesquare: StrictInt
    telecharge: StrictInt
    mpv: StrictInt
    etix: StrictInt
    ovationtix: StrictInt
    __properties: ClassVar[List[str]] = ["ticketmaster", "vividseats", "evenue", "tickpick", "stubhub", "gotickets", "milb", "mlb", "playhousesquare", "telecharge", "mpv", "etix", "ovationtix"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScrapedEventsCountSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScrapedEventsCountSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ticketmaster": obj.get("ticketmaster"),
            "vividseats": obj.get("vividseats"),
            "evenue": obj.get("evenue"),
            "tickpick": obj.get("tickpick"),
            "stubhub": obj.get("stubhub"),
            "gotickets": obj.get("gotickets"),
            "milb": obj.get("milb"),
            "mlb": obj.get("mlb"),
            "playhousesquare": obj.get("playhousesquare"),
            "telecharge": obj.get("telecharge"),
            "mpv": obj.get("mpv"),
            "etix": obj.get("etix"),
            "ovationtix": obj.get("ovationtix")
        })
        return _obj


