# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ScrapType(str, Enum):
    """
    ScrapType
    """

    """
    allowed enum values
    """
    TICKETMASTER_MINUS_MAP = 'ticketmaster-map'
    TICKETMASTER_MINUS_FACET = 'ticketmaster-facet'
    VIVIDSEATS = 'vividseats'
    EVENUE_MINUS_SEAT = 'evenue-seat'
    EVENUE_MINUS_SECTION = 'evenue-section'
    EVENUE_MINUS_PRICES = 'evenue-prices'
    STUBHUB = 'stubhub'
    TICKPICK = 'tickpick'
    GOTICKETS = 'gotickets'
    MILB = 'milb'
    MLB = 'mlb'
    GAMETIME = 'gametime'
    PLAYHOUSESQUARE = 'playhousesquare'
    TELECHARGE = 'telecharge'
    MPV = 'mpv'
    ETIX = 'etix'
    EVENTIM = 'eventim'
    OVATIONTIX = 'ovationtix'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ScrapType from a JSON string"""
        return cls(json.loads(json_str))


