# coding: utf-8

# flake8: noqa

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "EventsApi",
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "CategoryNameListSchema",
    "CategoryNameSchema",
    "CategoryTypeListSchema",
    "CategoryTypeSchema",
    "EventActiveSchema",
    "EventCookiesManagerResponseSchema",
    "EventExchange",
    "EventExchangeResponseSchema",
    "EventExchangeSchema",
    "EventMappingCreatedResponseSchema",
    "EventMappingCreatedSchema",
    "EventMappingListSchema",
    "EventMappingSchema",
    "EventSchema",
    "EventSearchSchema",
    "FormatInfo",
    "HTTPValidationError",
    "Order",
    "PaciolanEventMetadataSchema",
    "PerformerNameListSchema",
    "PerformerNameSchema",
    "PerformerTypeListSchema",
    "PerformerTypeSchema",
    "SecondaryExchange",
    "SimplifiedEventMappingsResponse",
    "StatusChangeTimestampSchema",
    "StatusChangedEventListSchema",
    "StatusChangedEventSchema",
    "ValidationError",
    "ValidationErrorLocInner",
    "VenueCityListSchema",
    "VenueCitySchema",
    "VenueCountryListSchema",
    "VenueCountrySchema",
    "VenueListSchema",
    "VenueMappingListSchema",
    "VenueMappingSchema",
    "VenueSchema",
    "VenueStateListSchema",
    "VenueStateSchema",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from events_api_client.api.events_api import EventsApi as EventsApi
    from events_api_client.api.default_api import DefaultApi as DefaultApi
    
    # import ApiClient
    from events_api_client.api_response import ApiResponse as ApiResponse
    from events_api_client.api_client import ApiClient as ApiClient
    from events_api_client.configuration import Configuration as Configuration
    from events_api_client.exceptions import OpenApiException as OpenApiException
    from events_api_client.exceptions import ApiTypeError as ApiTypeError
    from events_api_client.exceptions import ApiValueError as ApiValueError
    from events_api_client.exceptions import ApiKeyError as ApiKeyError
    from events_api_client.exceptions import ApiAttributeError as ApiAttributeError
    from events_api_client.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from events_api_client.models.category_name_list_schema import CategoryNameListSchema as CategoryNameListSchema
    from events_api_client.models.category_name_schema import CategoryNameSchema as CategoryNameSchema
    from events_api_client.models.category_type_list_schema import CategoryTypeListSchema as CategoryTypeListSchema
    from events_api_client.models.category_type_schema import CategoryTypeSchema as CategoryTypeSchema
    from events_api_client.models.event_active_schema import EventActiveSchema as EventActiveSchema
    from events_api_client.models.event_cookies_manager_response_schema import EventCookiesManagerResponseSchema as EventCookiesManagerResponseSchema
    from events_api_client.models.event_exchange import EventExchange as EventExchange
    from events_api_client.models.event_exchange_response_schema import EventExchangeResponseSchema as EventExchangeResponseSchema
    from events_api_client.models.event_exchange_schema import EventExchangeSchema as EventExchangeSchema
    from events_api_client.models.event_mapping_created_response_schema import EventMappingCreatedResponseSchema as EventMappingCreatedResponseSchema
    from events_api_client.models.event_mapping_created_schema import EventMappingCreatedSchema as EventMappingCreatedSchema
    from events_api_client.models.event_mapping_list_schema import EventMappingListSchema as EventMappingListSchema
    from events_api_client.models.event_mapping_schema import EventMappingSchema as EventMappingSchema
    from events_api_client.models.event_schema import EventSchema as EventSchema
    from events_api_client.models.event_search_schema import EventSearchSchema as EventSearchSchema
    from events_api_client.models.format_info import FormatInfo as FormatInfo
    from events_api_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
    from events_api_client.models.order import Order as Order
    from events_api_client.models.paciolan_event_metadata_schema import PaciolanEventMetadataSchema as PaciolanEventMetadataSchema
    from events_api_client.models.performer_name_list_schema import PerformerNameListSchema as PerformerNameListSchema
    from events_api_client.models.performer_name_schema import PerformerNameSchema as PerformerNameSchema
    from events_api_client.models.performer_type_list_schema import PerformerTypeListSchema as PerformerTypeListSchema
    from events_api_client.models.performer_type_schema import PerformerTypeSchema as PerformerTypeSchema
    from events_api_client.models.secondary_exchange import SecondaryExchange as SecondaryExchange
    from events_api_client.models.simplified_event_mappings_response import SimplifiedEventMappingsResponse as SimplifiedEventMappingsResponse
    from events_api_client.models.status_change_timestamp_schema import StatusChangeTimestampSchema as StatusChangeTimestampSchema
    from events_api_client.models.status_changed_event_list_schema import StatusChangedEventListSchema as StatusChangedEventListSchema
    from events_api_client.models.status_changed_event_schema import StatusChangedEventSchema as StatusChangedEventSchema
    from events_api_client.models.validation_error import ValidationError as ValidationError
    from events_api_client.models.validation_error_loc_inner import ValidationErrorLocInner as ValidationErrorLocInner
    from events_api_client.models.venue_city_list_schema import VenueCityListSchema as VenueCityListSchema
    from events_api_client.models.venue_city_schema import VenueCitySchema as VenueCitySchema
    from events_api_client.models.venue_country_list_schema import VenueCountryListSchema as VenueCountryListSchema
    from events_api_client.models.venue_country_schema import VenueCountrySchema as VenueCountrySchema
    from events_api_client.models.venue_list_schema import VenueListSchema as VenueListSchema
    from events_api_client.models.venue_mapping_list_schema import VenueMappingListSchema as VenueMappingListSchema
    from events_api_client.models.venue_mapping_schema import VenueMappingSchema as VenueMappingSchema
    from events_api_client.models.venue_schema import VenueSchema as VenueSchema
    from events_api_client.models.venue_state_list_schema import VenueStateListSchema as VenueStateListSchema
    from events_api_client.models.venue_state_schema import VenueStateSchema as VenueStateSchema
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from events_api_client.api.events_api import EventsApi as EventsApi
from events_api_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from events_api_client.api_response import ApiResponse as ApiResponse
from events_api_client.api_client import ApiClient as ApiClient
from events_api_client.configuration import Configuration as Configuration
from events_api_client.exceptions import OpenApiException as OpenApiException
from events_api_client.exceptions import ApiTypeError as ApiTypeError
from events_api_client.exceptions import ApiValueError as ApiValueError
from events_api_client.exceptions import ApiKeyError as ApiKeyError
from events_api_client.exceptions import ApiAttributeError as ApiAttributeError
from events_api_client.exceptions import ApiException as ApiException

# import models into sdk package
from events_api_client.models.category_name_list_schema import CategoryNameListSchema as CategoryNameListSchema
from events_api_client.models.category_name_schema import CategoryNameSchema as CategoryNameSchema
from events_api_client.models.category_type_list_schema import CategoryTypeListSchema as CategoryTypeListSchema
from events_api_client.models.category_type_schema import CategoryTypeSchema as CategoryTypeSchema
from events_api_client.models.event_active_schema import EventActiveSchema as EventActiveSchema
from events_api_client.models.event_cookies_manager_response_schema import EventCookiesManagerResponseSchema as EventCookiesManagerResponseSchema
from events_api_client.models.event_exchange import EventExchange as EventExchange
from events_api_client.models.event_exchange_response_schema import EventExchangeResponseSchema as EventExchangeResponseSchema
from events_api_client.models.event_exchange_schema import EventExchangeSchema as EventExchangeSchema
from events_api_client.models.event_mapping_created_response_schema import EventMappingCreatedResponseSchema as EventMappingCreatedResponseSchema
from events_api_client.models.event_mapping_created_schema import EventMappingCreatedSchema as EventMappingCreatedSchema
from events_api_client.models.event_mapping_list_schema import EventMappingListSchema as EventMappingListSchema
from events_api_client.models.event_mapping_schema import EventMappingSchema as EventMappingSchema
from events_api_client.models.event_schema import EventSchema as EventSchema
from events_api_client.models.event_search_schema import EventSearchSchema as EventSearchSchema
from events_api_client.models.format_info import FormatInfo as FormatInfo
from events_api_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from events_api_client.models.order import Order as Order
from events_api_client.models.paciolan_event_metadata_schema import PaciolanEventMetadataSchema as PaciolanEventMetadataSchema
from events_api_client.models.performer_name_list_schema import PerformerNameListSchema as PerformerNameListSchema
from events_api_client.models.performer_name_schema import PerformerNameSchema as PerformerNameSchema
from events_api_client.models.performer_type_list_schema import PerformerTypeListSchema as PerformerTypeListSchema
from events_api_client.models.performer_type_schema import PerformerTypeSchema as PerformerTypeSchema
from events_api_client.models.secondary_exchange import SecondaryExchange as SecondaryExchange
from events_api_client.models.simplified_event_mappings_response import SimplifiedEventMappingsResponse as SimplifiedEventMappingsResponse
from events_api_client.models.status_change_timestamp_schema import StatusChangeTimestampSchema as StatusChangeTimestampSchema
from events_api_client.models.status_changed_event_list_schema import StatusChangedEventListSchema as StatusChangedEventListSchema
from events_api_client.models.status_changed_event_schema import StatusChangedEventSchema as StatusChangedEventSchema
from events_api_client.models.validation_error import ValidationError as ValidationError
from events_api_client.models.validation_error_loc_inner import ValidationErrorLocInner as ValidationErrorLocInner
from events_api_client.models.venue_city_list_schema import VenueCityListSchema as VenueCityListSchema
from events_api_client.models.venue_city_schema import VenueCitySchema as VenueCitySchema
from events_api_client.models.venue_country_list_schema import VenueCountryListSchema as VenueCountryListSchema
from events_api_client.models.venue_country_schema import VenueCountrySchema as VenueCountrySchema
from events_api_client.models.venue_list_schema import VenueListSchema as VenueListSchema
from events_api_client.models.venue_mapping_list_schema import VenueMappingListSchema as VenueMappingListSchema
from events_api_client.models.venue_mapping_schema import VenueMappingSchema as VenueMappingSchema
from events_api_client.models.venue_schema import VenueSchema as VenueSchema
from events_api_client.models.venue_state_list_schema import VenueStateListSchema as VenueStateListSchema
from events_api_client.models.venue_state_schema import VenueStateSchema as VenueStateSchema

""",
            name=__name__,
            doc=__doc__,
        )
    )
