# coding: utf-8

# flake8: noqa
"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from events_api_client.models.category_name_list_schema import CategoryNameListSchema
    from events_api_client.models.category_name_schema import CategoryNameSchema
    from events_api_client.models.category_type_list_schema import CategoryTypeListSchema
    from events_api_client.models.category_type_schema import CategoryTypeSchema
    from events_api_client.models.event_active_schema import EventActiveSchema
    from events_api_client.models.event_cookies_manager_response_schema import EventCookiesManagerResponseSchema
    from events_api_client.models.event_exchange import EventExchange
    from events_api_client.models.event_exchange_response_schema import EventExchangeResponseSchema
    from events_api_client.models.event_exchange_schema import EventExchangeSchema
    from events_api_client.models.event_mapping_created_response_schema import EventMappingCreatedResponseSchema
    from events_api_client.models.event_mapping_created_schema import EventMappingCreatedSchema
    from events_api_client.models.event_mapping_list_schema import EventMappingListSchema
    from events_api_client.models.event_mapping_schema import EventMappingSchema
    from events_api_client.models.event_schema import EventSchema
    from events_api_client.models.event_search_schema import EventSearchSchema
    from events_api_client.models.format_info import FormatInfo
    from events_api_client.models.http_validation_error import HTTPValidationError
    from events_api_client.models.order import Order
    from events_api_client.models.paciolan_event_metadata_schema import PaciolanEventMetadataSchema
    from events_api_client.models.performer_name_list_schema import PerformerNameListSchema
    from events_api_client.models.performer_name_schema import PerformerNameSchema
    from events_api_client.models.performer_type_list_schema import PerformerTypeListSchema
    from events_api_client.models.performer_type_schema import PerformerTypeSchema
    from events_api_client.models.secondary_exchange import SecondaryExchange
    from events_api_client.models.simplified_event_mappings_response import SimplifiedEventMappingsResponse
    from events_api_client.models.status_change_timestamp_schema import StatusChangeTimestampSchema
    from events_api_client.models.status_changed_event_list_schema import StatusChangedEventListSchema
    from events_api_client.models.status_changed_event_schema import StatusChangedEventSchema
    from events_api_client.models.validation_error import ValidationError
    from events_api_client.models.validation_error_loc_inner import ValidationErrorLocInner
    from events_api_client.models.venue_city_list_schema import VenueCityListSchema
    from events_api_client.models.venue_city_schema import VenueCitySchema
    from events_api_client.models.venue_country_list_schema import VenueCountryListSchema
    from events_api_client.models.venue_country_schema import VenueCountrySchema
    from events_api_client.models.venue_list_schema import VenueListSchema
    from events_api_client.models.venue_mapping_list_schema import VenueMappingListSchema
    from events_api_client.models.venue_mapping_schema import VenueMappingSchema
    from events_api_client.models.venue_schema import VenueSchema
    from events_api_client.models.venue_state_list_schema import VenueStateListSchema
    from events_api_client.models.venue_state_schema import VenueStateSchema
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from events_api_client.models.category_name_list_schema import CategoryNameListSchema
from events_api_client.models.category_name_schema import CategoryNameSchema
from events_api_client.models.category_type_list_schema import CategoryTypeListSchema
from events_api_client.models.category_type_schema import CategoryTypeSchema
from events_api_client.models.event_active_schema import EventActiveSchema
from events_api_client.models.event_cookies_manager_response_schema import EventCookiesManagerResponseSchema
from events_api_client.models.event_exchange import EventExchange
from events_api_client.models.event_exchange_response_schema import EventExchangeResponseSchema
from events_api_client.models.event_exchange_schema import EventExchangeSchema
from events_api_client.models.event_mapping_created_response_schema import EventMappingCreatedResponseSchema
from events_api_client.models.event_mapping_created_schema import EventMappingCreatedSchema
from events_api_client.models.event_mapping_list_schema import EventMappingListSchema
from events_api_client.models.event_mapping_schema import EventMappingSchema
from events_api_client.models.event_schema import EventSchema
from events_api_client.models.event_search_schema import EventSearchSchema
from events_api_client.models.format_info import FormatInfo
from events_api_client.models.http_validation_error import HTTPValidationError
from events_api_client.models.order import Order
from events_api_client.models.paciolan_event_metadata_schema import PaciolanEventMetadataSchema
from events_api_client.models.performer_name_list_schema import PerformerNameListSchema
from events_api_client.models.performer_name_schema import PerformerNameSchema
from events_api_client.models.performer_type_list_schema import PerformerTypeListSchema
from events_api_client.models.performer_type_schema import PerformerTypeSchema
from events_api_client.models.secondary_exchange import SecondaryExchange
from events_api_client.models.simplified_event_mappings_response import SimplifiedEventMappingsResponse
from events_api_client.models.status_change_timestamp_schema import StatusChangeTimestampSchema
from events_api_client.models.status_changed_event_list_schema import StatusChangedEventListSchema
from events_api_client.models.status_changed_event_schema import StatusChangedEventSchema
from events_api_client.models.validation_error import ValidationError
from events_api_client.models.validation_error_loc_inner import ValidationErrorLocInner
from events_api_client.models.venue_city_list_schema import VenueCityListSchema
from events_api_client.models.venue_city_schema import VenueCitySchema
from events_api_client.models.venue_country_list_schema import VenueCountryListSchema
from events_api_client.models.venue_country_schema import VenueCountrySchema
from events_api_client.models.venue_list_schema import VenueListSchema
from events_api_client.models.venue_mapping_list_schema import VenueMappingListSchema
from events_api_client.models.venue_mapping_schema import VenueMappingSchema
from events_api_client.models.venue_schema import VenueSchema
from events_api_client.models.venue_state_list_schema import VenueStateListSchema
from events_api_client.models.venue_state_schema import VenueStateSchema

""",
            name=__name__,
            doc=__doc__,
        )
    )
