# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class StatusChangedEventSchema(BaseModel):
    """
    StatusChangedEventSchema
    """ # noqa: E501
    event_id: StrictStr
    name: StrictStr
    venue_name: Optional[StrictStr]
    local_date: Optional[datetime]
    url: Optional[StrictStr]
    vividseats_url: Optional[StrictStr]
    viagogo_url: Optional[StrictStr]
    venue_id: StrictStr
    __properties: ClassVar[List[str]] = ["event_id", "name", "venue_name", "local_date", "url", "vividseats_url", "viagogo_url", "venue_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StatusChangedEventSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if venue_name (nullable) is None
        # and model_fields_set contains the field
        if self.venue_name is None and "venue_name" in self.model_fields_set:
            _dict['venue_name'] = None

        # set to None if local_date (nullable) is None
        # and model_fields_set contains the field
        if self.local_date is None and "local_date" in self.model_fields_set:
            _dict['local_date'] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        # set to None if vividseats_url (nullable) is None
        # and model_fields_set contains the field
        if self.vividseats_url is None and "vividseats_url" in self.model_fields_set:
            _dict['vividseats_url'] = None

        # set to None if viagogo_url (nullable) is None
        # and model_fields_set contains the field
        if self.viagogo_url is None and "viagogo_url" in self.model_fields_set:
            _dict['viagogo_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StatusChangedEventSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event_id": obj.get("event_id"),
            "name": obj.get("name"),
            "venue_name": obj.get("venue_name"),
            "local_date": obj.get("local_date"),
            "url": obj.get("url"),
            "vividseats_url": obj.get("vividseats_url"),
            "viagogo_url": obj.get("viagogo_url"),
            "venue_id": obj.get("venue_id")
        })
        return _obj


